"""Restyle the existing ProjectHunter menu through Unreal's supported editor API.

Run with Unreal's Python plugin, never with the system Python interpreter.
Default: exercise the edits in memory without saving. Pass --apply to back up,
check Blueprint contracts, compile, and save only the eleven allowlisted menus.
Use -ExecutePythonScript (initialized editor/Slate), not -run=pythonscript.
Close other editors of this project before running a separate editor to save assets.
This script does not create widgets, edit graphs, or modify the player HUD.
"""

import argparse
from datetime import datetime
import hashlib
import json
from pathlib import Path
import shutil

import unreal


ASSET_ROOT = "/Game/ProjectHunter/UI/Widgets/Menus/"
# Compile reusable leaves before their consumers. Names are Blueprint contracts.
MENUS = (
    "Equipment/WBP_VitalBar",
    "Equipment/WBP_EquipmentSlot",
    "Equipment/WBP_InventorySlot",
    "System/WBP_SystemMenuTab",
    "Equipment/WBP_CharacterPreview",
    "Equipment/WBP_VitalsPanel",
    "Equipment/WBP_EquipmentPanel",
    "Equipment/WBP_InventoryPanel",
    "System/WBP_SystemMenuHeader",
    "Equipment/WBP_EquipmentPage",
    "System/WBP_SystemMenuRoot",
)

# The System-window palette. Azure and AzureDeep are the same values PHUIStyle.h
# declares in linear space; that header and this script have to agree or the C++
# and UMG halves of the menu drift apart.
#
# The window body is bright azure and the line language is white, matching the
# system-window reference. Content blocks sit *darker* than the body so item
# icons and bars stay readable against it - only the outer window is chamfered.
# Depth ramp, lightest to darkest: panel (window body) -> surface (content
# blocks, unselected tabs) -> ink (slot wells, bar tracks).
# panel and surface are exactly PHUIStyle::Azure and PHUIStyle::AzureDeep.
PALETTE = {
    "ink": "071B33", "panel": "2E9BE0", "surface": "1C4F9E",
    "hover": "5FBDF2", "edge": "FFFFFF", "accent": "9BE0FF",
    "text": "FFFFFF", "dim": "C8E6FA", "selected": "BFE9FF",
    # Section headers. Teal-leaning cyan (green and blue equal, red low) so it
    # reads as a distinct accent against the azure body rather than as a paler
    # shade of it - "dim" and "accent" are both blue-leaning and disappear into
    # the panel. One constant: retune here and reapply.
    "header": "8FE3DC",
    "health": "A8DA73", "mana": "62CDEC", "stamina": "DFC783",
    "shield": "BBA6ED", "track": "071B33", "white": "FFFFFF",
}
CELL_SIZE = 96.0

# The chamfered window art, regenerated by MakeSystemPanelTextures.py.
# Fill is the translucent body plus its opaque white double line; Frame is that
# line alone, for reuse on any other panel.
SYSTEM_TEXTURES = {
    "fill": ASSET_ROOT + "System/T_SystemPanel_Fill",
    "frame": ASSET_ROOT + "System/T_SystemPanel_Frame",
    # Silhouette for M_SquareFlicker's MaskValue, so the accents follow the
    # window shape. Not a brush - imported and saved with the others.
    "mask": ASSET_ROOT + "System/T_SystemPanel_Mask",
}

# A mask carries data, not colour: sRGB would bend its 0..1 ramp.
LINEAR_TEXTURES = {"mask"}

# The floating corner squares are a material, not painted into the texture, so
# they animate and any menu can reuse them.
SQUARE_FLICKER = "/Game/ProjectHunter/Textures/Materials/M_SquareFlicker"

# 256px power-of-two art with a 40px chamfer; the 48px corner block contains the
# whole chamfer, so stretching only touches the flat middle run of each edge.
# Must match the value MakeSystemPanelTextures.py prints.
SYSTEM_MARGIN = 48.0 / 256.0
SYSTEM_TEXTURE_SIZE = 256.0
H = unreal.HorizontalAlignment
V = unreal.VerticalAlignment


def color(key, alpha=1.0):
    value = PALETTE[key]

    def linear(channel):
        channel = int(channel, 16) / 255.0
        return channel / 12.92 if channel <= 0.04045 else ((channel + 0.055) / 1.055) ** 2.4

    return unreal.LinearColor(*(linear(value[i:i + 2]) for i in (0, 2, 4)), alpha)


def slate_color(key, alpha=1.0):
    return unreal.SlateColor(specified_color=color(key, alpha))


def margin(left=0.0, top=None, right=None, bottom=None):
    return unreal.Margin(left, left if top is None else top,
                         left if right is None else right, left if bottom is None else bottom)


def brush(fill="panel", alpha=1.0, edge="edge", edge_alpha=0.0, radius=4.0, width=1.0):
    outline = unreal.SlateBrushOutlineSettings(
        corner_radii=unreal.Vector4(radius, radius, radius, radius),
        color=slate_color(edge, edge_alpha), width=width,
        rounding_type=unreal.SlateBrushRoundingType.FIXED_RADIUS,
        use_brush_transparency=False)
    result = unreal.SlateBrush()
    result.set_editor_properties({
        "draw_as": unreal.SlateBrushDrawType.ROUNDED_BOX,
        "tint_color": slate_color(fill, alpha), "outline_settings": outline,
    })
    return result


def slate_image_size(x, y):
    """Build a value for SlateBrush.ImageSize.

    UE 5.7 types that property as DeprecateSlateVector2D, which rejects Vector2D
    and takes no constructor arguments, so it has to be filled in after
    construction. It matters for a BOX brush: Slate sizes the nine-slice corners
    from ImageSize, and a zero here collapses them.
    """
    value = unreal.DeprecateSlateVector2D()
    try:
        value.set_editor_property("x", float(x))
        value.set_editor_property("y", float(y))
    except Exception:
        value.x = float(x)
        value.y = float(y)
    return value


def texture_brush(which, tint="white", alpha=1.0):
    """A 9-slice brush over the chamfered window art.

    BOX rather than IMAGE: the menu is resized by anchors, and a stretched
    IMAGE would shear the chamfers.

    Tint stays opaque white by default. The body's translucency is baked into
    the texture's alpha instead, because a tint alpha would fade the white
    double line along with the body and the window would stop reading as a
    frame - which is exactly what happened on the first pass.
    """
    texture = unreal.EditorAssetLibrary.load_asset(SYSTEM_TEXTURES[which])
    if texture is None:
        raise RuntimeError("Missing system panel texture: " + SYSTEM_TEXTURES[which])
    size = texture.blueprint_get_size_x()
    if size != int(SYSTEM_TEXTURE_SIZE):
        raise RuntimeError(
            "%s is %dpx; expected %d. Run MakeSystemPanelTextures.py and reimport - a "
            "non-power-of-two panel texture distorts." % (SYSTEM_TEXTURES[which], size, SYSTEM_TEXTURE_SIZE))
    result = unreal.SlateBrush()
    result.set_editor_properties({
        "draw_as": unreal.SlateBrushDrawType.BOX,
        "margin": margin(SYSTEM_MARGIN),
        "tint_color": slate_color(tint, alpha),
        "resource_object": texture,
        # UE 5.7 types SlateBrush.ImageSize as DeprecateSlateVector2D, not
        # Vector2D, and rejects the latter outright.
        "image_size": slate_image_size(SYSTEM_TEXTURE_SIZE, SYSTEM_TEXTURE_SIZE),
    })
    return result


def material_brush(path, alpha=1.0):
    """A brush that renders an authored UI material.

    Used for the corner accents so they can animate. A material only draws in
    UMG when its domain is User Interface; anything else silently renders
    nothing, so that is checked here rather than left to look like a bug.
    """
    material = unreal.EditorAssetLibrary.load_asset(path)
    if material is None:
        raise RuntimeError("Missing material: " + path)
    domain = material.get_editor_property("material_domain")
    if domain != unreal.MaterialDomain.MD_UI:
        raise RuntimeError(
            "%s has domain %s; UMG needs Material Domain 'User Interface' or it draws "
            "nothing." % (path, domain))
    result = unreal.SlateBrush()
    result.set_editor_properties({
        "draw_as": unreal.SlateBrushDrawType.IMAGE,
        "tint_color": slate_color("white", alpha),
        "resource_object": material,
    })
    return result


def set_slot(widget, **properties):
    slot = widget.get_editor_property("slot")
    if slot is None:
        raise RuntimeError("Expected a layout slot for " + widget.get_path_name())
    slot.modify()
    slot.set_editor_properties(properties)


def set_text(widget, size, tone="text", text=None, weight="SemiBold", spacing=0, shadow=False):
    """Style one label.

    `shadow` is for text drawn over the window's transparent centre, where the
    backdrop is the live world and can be any colour. A flat tint that reads on
    one scene disappears on the next; a one-pixel dark offset keeps it legible
    on all of them.
    """
    font = widget.get_editor_property("font")
    font.set_editor_properties({"size": size, "typeface_font_name": weight, "letter_spacing": spacing})
    widget.set_editor_properties({"font": font, "color_and_opacity": slate_color(tone),
                                  "shadow_offset": unreal.Vector2D(1.0, 1.0) if shadow
                                                   else unreal.Vector2D(0.0, 0.0),
                                  "shadow_color_and_opacity": color("ink", 0.65 if shadow else 0.0)})
    if text is not None:
        widget.set_editor_property("text", text)


def set_border(widget, fill="surface", alpha=0.72, edge_alpha=0.55, padding=16.0):
    widget.set_editor_properties({"background": brush(fill, alpha, edge_alpha=edge_alpha, radius=5.0),
                                  "brush_color": color("white"), "padding": margin(padding)})


def button_style(button, native_tint=False):
    style = button.get_editor_property("widget_style")
    if native_tint:
        # PHMenuTabButtonWidget already drives background/text tints on selection
        # and hover. White brushes let those existing authored fields stay in charge.
        normal = brush("white", edge="white", edge_alpha=0.25)
        hover = brush("white", edge="white", edge_alpha=0.55)
        pressed = brush("white", 0.9, edge="white", edge_alpha=0.75)
    else:
        normal = brush("surface", 0.9, edge_alpha=0.35)
        hover = brush("hover", edge="accent", edge_alpha=0.8)
        pressed = brush("selected", edge="accent", edge_alpha=1.0)
    style.set_editor_properties({"normal": normal, "hovered": hover, "pressed": pressed,
                                 "normal_padding": margin(0), "pressed_padding": margin(0)})
    button.set_editor_property("widget_style", style)


def scroll_style(scroll):
    scroll.set_editor_properties({"scrollbar_thickness": unreal.Vector2D(3.0, 3.0),
                                  "scrollbar_padding": margin(8.0, 0.0, 0.0, 0.0)})
    style = scroll.get_editor_property("widget_bar_style")
    style.set_editor_properties({
        "normal_thumb_image": brush("edge", 0.7, radius=1.5),
        "hovered_thumb_image": brush("accent", 0.85, radius=1.5),
        "dragged_thumb_image": brush("accent", radius=1.5),
        "vertical_background_image": brush("ink", 0.5, radius=1.5),
    })
    scroll.set_editor_property("widget_bar_style", style)
    box_style = scroll.get_editor_property("widget_style")
    for name in ("top_shadow_brush", "bottom_shadow_brush", "left_shadow_brush", "right_shadow_brush"):
        box_style.set_editor_property(name, brush(alpha=0.0))
    scroll.set_editor_property("widget_style", box_style)


def widgets(asset):
    prefix = asset.get_path_name() + ":WidgetTree."
    return {widget.get_name(): widget for widget in unreal.ObjectIterator(unreal.Widget)
            if widget.get_path_name().startswith(prefix)}


def cdo(asset):
    return unreal.get_default_object(unreal.EditorAssetLibrary.load_blueprint_class(asset.get_path_name()))


def style_asset(name, asset):
    w = widgets(asset)
    for widget in w.values():
        widget.modify()
    defaults = cdo(asset)
    defaults.modify()

    if name.endswith("WBP_SystemMenuRoot"):
        set_border(w["ScreenDim"], "ink", alpha=0.55, edge_alpha=0.0, padding=0.0)
        # The window body is the authored chamfered art, not a rounded box. A
        # native ROUNDED_BOX here is what flattened the system window into a
        # plain rectangle and discarded the corner accents entirely.
        # Body and its white double line, both from the one texture. Opaque
        # tint: the body's transparency is in the texture's own alpha.
        w["MenuFrameImage"].set_editor_property("brush", texture_brush("fill"))
        set_slot(w["MenuFrameImage"], horizontal_alignment=H.H_ALIGN_FILL,
                 vertical_alignment=V.V_ALIGN_FILL, padding=margin(0.0))
        # The animated corner accents, over the frame. This image was already a
        # decorative overlay in the authored tree, so it keeps its name and role
        # - but it ships Hidden, which is why the first pass drew no accents at
        # all. Making it visible is a deliberate presentation change and is
        # excluded from the contract diff in functional_contract().
        w["ScanlineSweep"].set_editor_properties({
            "brush": material_brush(SQUARE_FLICKER),
            "color_and_opacity": color("white", 1.0),
            "visibility": unreal.SlateVisibility.SELF_HIT_TEST_INVISIBLE,
        })
        set_slot(w["ScanlineSweep"], horizontal_alignment=H.H_ALIGN_FILL,
                 vertical_alignment=V.V_ALIGN_FILL, padding=margin(0.0))
        set_slot(w["SystemFrame"], layout_data=unreal.AnchorData(
            offsets=margin(24.0), anchors=unreal.Anchors(unreal.Vector2D(0, 0), unreal.Vector2D(1, 1)),
            alignment=unreal.Vector2D(0, 0)))
        set_slot(w["MenuContent"], padding=margin(24.0, 20.0, 24.0, 24.0))
        set_text(w["SystemTitle"], 25, text="PROJECT HUNTER / SYSTEM", spacing=120)
        w["SystemTitle"].set_editor_property("justification", unreal.TextJustify.LEFT)
        set_slot(w["SystemTitle"], padding=margin(0.0, 0.0, 0.0, 3.0))
        set_text(w["SystemSubtitle"], 11, "header", spacing=160)
        w["SystemSubtitle"].set_editor_property("justification", unreal.TextJustify.LEFT)
        set_slot(w["SystemSubtitle"], padding=margin(0.0, 0.0, 0.0, 10.0))
        set_slot(w["TabBar"], padding=margin(0.0, 0.0, 0.0, 18.0))
        w["CloseButtonSize"].set_width_override(36.0)
        w["CloseButtonSize"].set_height_override(36.0)
        set_slot(w["CloseButtonSize"], padding=margin(0.0, 20.0, 24.0, 0.0))
        button_style(w["CloseButton"])
        set_text(w["CloseButtonText"], 16, "text")

    elif name.endswith("WBP_SystemMenuHeader"):
        w["HeaderBackground"].set_editor_properties({"padding": margin(0), "horizontal_alignment": H.H_ALIGN_LEFT})
        set_slot(w["TabContainer"], padding=margin(0), horizontal_alignment=H.H_ALIGN_LEFT)

    elif name.endswith("WBP_SystemMenuTab"):
        w["TabSize"].set_min_desired_width(174.0)
        w["TabSize"].set_height_override(42.0)
        button_style(w["TabButton"], native_tint=True)
        set_slot(w["TabButton"], padding=margin(0.0, 0.0, 6.0, 0.0))
        set_slot(w["TabLabel"], padding=margin(16.0, 0.0, 16.0, 0.0))
        set_text(w["TabLabel"], 15, spacing=20)
        # Selected tab inverts, as the reference window does: a bright chip with
        # deep text. White-on-pale would be unreadable, so the selected label
        # goes to the darkest ink rather than to TextPrimary.
        defaults.set_editor_properties({"normal_color": color("surface"), "hovered_color": color("hover"),
            "selected_color": color("selected"), "normal_text_color": color("dim"), "selected_text_color": color("ink")})

    elif name.endswith("WBP_EquipmentPage"):
        for spacer in ("Spacer_EquipmentPreview", "Spacer_PreviewInventory"):
            w[spacer].set_editor_property("size", unreal.Vector2D(18.0, 0.0))
        set_slot(w["WBP_CharacterPreview"], padding=margin(0.0, 0.0, 0.0, 14.0))
        w["VitalsSize"].set_height_override(218.0)
        w["InventoryPanel"].set_editor_property("inventory_cell_size", unreal.Vector2D(CELL_SIZE, CELL_SIZE))

    elif name.endswith("WBP_EquipmentPanel") or name.endswith("WBP_InventoryPanel"):
        kind = "Equipment" if name.endswith("WBP_EquipmentPanel") else "Inventory"
        set_border(w[kind + "PanelBackground"], padding=16.0)
        set_slot(w[kind + "PanelColumn"], padding=margin(0))
        set_text(w[kind + "HeaderText"], 17, "header", text=kind.upper(), spacing=90)
        w[kind + "HeaderText"].set_editor_property("justification", unreal.TextJustify.LEFT)
        set_slot(w[kind + "HeaderText"], padding=margin(4.0, 0.0, 0.0, 14.0))
        w[kind + "SlotContainer"].set_editor_property("slot_padding", margin(4.0))
        set_slot(w[kind + "SlotContainer"],
                 size=unreal.SlateChildSize(value=1.0, size_rule=unreal.SlateSizeRule.AUTOMATIC),
                 vertical_alignment=V.V_ALIGN_TOP)
        scroll_style(w[kind + "Scroll"])
        if kind == "Inventory":
            defaults.set_editor_property("inventory_cell_size", unreal.Vector2D(CELL_SIZE, CELL_SIZE))

    elif name.endswith("WBP_EquipmentSlot") or name.endswith("WBP_InventorySlot"):
        w["SlotSize"].set_width_override(CELL_SIZE)
        w["SlotSize"].set_height_override(CELL_SIZE)
        # Depth ramp, lightest to darkest: panel body -> panel blocks -> slot
        # wells. Slots are the darkest step so item icons read against them.
        set_border(w["SlotOutline"], alpha=0.0, edge_alpha=0.60, padding=0.0)
        set_border(w["SlotSurface"], "ink", alpha=0.55, edge_alpha=0.0, padding=0.0)
        set_slot(w["SlotSurface"], padding=margin(1.0))
        set_slot(w["ItemIcon"], padding=margin(14.0))
        set_slot(w["SlotLabels"], padding=margin(6.0))
        set_text(w["ItemNameText"], 10, "dim", weight="Regular")
        w["ItemNameText"].set_editor_property("text_overflow_policy", unreal.TextOverflowPolicy.ELLIPSIS)
        if "SlotButton" in w:
            button_style(w["SlotButton"])
            set_text(w["SlotNameText"], 12, "dim", weight="Regular")
        if "StackText" in w:
            set_text(w["StackText"], 12)

    elif name.endswith("WBP_CharacterPreview"):
        set_border(w["PreviewHitArea"], alpha=0.0, edge_alpha=0.3, padding=0.0)
        set_text(w["PreviewHeaderText"], 12, "header", text="CHARACTER", spacing=140, shadow=True)
        set_slot(w["PreviewHeaderText"], padding=margin(0.0, 16.0, 0.0, 0.0))
        set_text(w["CharacterNameText"], 20, spacing=100, shadow=True)
        set_text(w["PreviewHintText"], 12, "header", weight="Regular", text="DRAG TO ROTATE   /   SCROLL TO ZOOM", shadow=True)
        set_slot(w["PreviewFooter"], padding=margin(0.0, 0.0, 0.0, 18.0))

    elif name.endswith("WBP_VitalsPanel"):
        set_border(w["VitalsPanelBackground"], padding=16.0)
        set_slot(w["VitalsColumn"], padding=margin(0))
        set_text(w["VitalsHeaderText"], 12, "header", text="VITALS", spacing=120)
        w["VitalsHeaderText"].set_editor_property("justification", unreal.TextJustify.LEFT)
        set_slot(w["VitalsHeaderText"], padding=margin(0.0, 0.0, 0.0, 8.0))
        for widget_name, tone in (("HealthVital", "health"), ("StaminaVital", "stamina"),
                                  ("ManaVital", "mana"), ("ArcaneShieldVital", "shield")):
            # These are existing menu-only resource widgets. Attribute mappings,
            # delegates, interpolation, visibility policy and HUD bars stay intact.
            w[widget_name].set_editor_properties({"current_fill_color": color(tone), "bar_height_override": 7.0})
            set_slot(w[widget_name], padding=margin(0.0, 4.0, 0.0, 4.0))

    elif name.endswith("WBP_VitalBar"):
        set_border(w["VitalBackground"], alpha=0.0, edge_alpha=0.0, padding=0.0)
        set_slot(w["VitalColumn"], padding=margin(0))
        set_text(w["ResourceNameText"], 12, "dim", weight="Regular")
        set_text(w["ResourceValueText"], 12)
        set_slot(w["VitalLabels"], padding=margin(0.0, 0.0, 0.0, 4.0))
        w["BarSize"].set_min_desired_height(7.0)
        for bar_name in ("Bar_DamageLag", "Bar_Current", "Bar_Reserved"):
            style = w[bar_name].get_editor_property("widget_style")
            style.set_editor_properties({
                "background_image": brush("track", 1.0 if bar_name == "Bar_DamageLag" else 0.0, radius=2.0),
                "fill_image": brush("white", radius=2.0),
            })
            w[bar_name].set_editor_property("widget_style", style)
            set_slot(w[bar_name], vertical_alignment=V.V_ALIGN_FILL)


def functional_contract(report):
    """Exclude only the presentation fields this script deliberately authors."""
    visual_config = {"InventoryCellSize", "NormalColor", "HoveredColor", "SelectedColor", "NormalTextColor", "SelectedTextColor"}

    def configuration(value, menu_vital=False):
        return {key: val for key, val in value.items() if key not in visual_config
                and not (menu_vital and key == "BarHeightOverride")}

    return [{"asset": asset["asset"], "parent": asset["parent_class"], "native_parent": asset["native_parent"],
             "class": asset["generated_class"], "contracts": asset["contracts"],
             "configuration": configuration(asset["configuration"]),
             "widgets": [{"name": w["name"], "class": w["class"], "parent": w["parent"],
                          "slot_class": w.get("slot_class"),
                          "configuration": configuration(w["configuration"],
                              asset["asset"].endswith("WBP_VitalsPanel.WBP_VitalsPanel") and
                              w["name"] in {"HealthVital", "StaminaVital", "ManaVital", "ArcaneShieldVital"}),
                          # ScanlineSweep ships Hidden and is a purely decorative
                          # overlay. Revealing it is the one visibility change
                          # this script makes; everything else must still match.
                          "visibility": None if w["name"] == "ScanlineSweep"
                              else w["properties"].get("Visibility"),
                          "enabled": w["properties"].get("bIsEnabled")}
                         for w in asset["widgets"]]}
            for asset in report["assets"]]


def reimport_system_textures():
    """Reimport the panel PNGs and pin the settings a UI texture needs.

    Returns the reimported texture assets so the caller can save them.

    NoMipmaps and the UI group matter as much as the power-of-two size: a
    mipped, world-grouped panel texture is filtered and resized by the streamer
    and the crisp one-pixel line goes soft.
    """
    tools = unreal.AssetToolsHelpers.get_asset_tools()
    content = Path(unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_content_dir()))
    reimported = []
    for key, path in SYSTEM_TEXTURES.items():
        folder, name = path.rsplit("/", 1)
        source = content / "ProjectHunter/UI/Widgets/Menus/System" / (name + ".png")
        if not source.exists():
            raise RuntimeError("Missing texture source; run MakeSystemPanelTextures.py: " + str(source))
        task = unreal.AssetImportTask()
        task.set_editor_properties({
            "filename": str(source), "destination_path": folder, "destination_name": name,
            "replace_existing": True, "automated": True, "save": False,
        })
        tools.import_asset_tasks([task])
        texture = unreal.EditorAssetLibrary.load_asset(path)
        if texture is None:
            raise RuntimeError("Reimport produced no asset: " + path)
        texture.modify()
        texture.set_editor_properties({
            "lod_group": unreal.TextureGroup.TEXTUREGROUP_UI,
            "compression_settings": unreal.TextureCompressionSettings.TC_EDITOR_ICON,
            "mip_gen_settings": unreal.TextureMipGenSettings.TMGS_NO_MIPMAPS,
            "srgb": key not in LINEAR_TEXTURES,
        })
        reimported.append(texture)
    return reimported


def backup_assets(output):
    content = Path(unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_content_dir()))
    manifest = []
    # The panel textures are reimported and saved too, so they are backed up
    # alongside the Blueprints - including the .png, which is overwritten by
    # MakeSystemPanelTextures.py rather than by this script.
    textures = ["System/T_SystemPanel_Fill", "System/T_SystemPanel_Frame",
                "System/T_SystemPanel_Mask"]
    for name in list(MENUS) + textures:
        relative = Path("ProjectHunter/UI/Widgets/Menus") / name
        for suffix in (".uasset", ".uexp", ".ubulk", ".png"):
            source = (content / relative).with_suffix(suffix)
            if not source.exists():
                # A texture may be new - generated as a .png and not imported
                # yet - so there is nothing to back up. A missing Blueprint is
                # still an error: this script never creates one.
                if suffix == ".uasset" and name not in textures:
                    raise RuntimeError("Missing source asset: " + str(source))
                continue
            destination = (output / "Backup" / relative).with_suffix(suffix)
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
            digest = hashlib.sha256(source.read_bytes()).hexdigest()
            if hashlib.sha256(destination.read_bytes()).hexdigest() != digest:
                raise RuntimeError("Backup verification failed: " + str(source))
            manifest.append({"source": str(source), "backup": str(destination), "sha256": digest})
    (output / "BackupManifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="Back up, validate, compile and save the menu assets")
    parser.add_argument("--output", help="New evidence directory; existing directories are never overwritten")
    args = parser.parse_args(argv)
    output = Path(args.output) if args.output else Path(unreal.Paths.project_saved_dir()) / "MenuPolish" / datetime.now().strftime("%Y%m%d-%H%M%S")
    output = output.resolve()
    if output.exists():
        raise RuntimeError("Use a new output directory so earlier backups remain intact: " + str(output))
    output.mkdir(parents=True)

    dirty = {p.get_name() for p in unreal.EditorLoadingAndSavingUtils.get_dirty_content_packages()}
    targets = {ASSET_ROOT + name for name in MENUS}
    if dirty & targets:
        raise RuntimeError("Save or discard your own unsaved menu edits before running: " + str(sorted(dirty & targets)))
    assets = {name: unreal.load_asset(ASSET_ROOT + name) for name in MENUS}
    if any(not asset or asset.get_class().get_name() != "WidgetBlueprint" for asset in assets.values()):
        raise RuntimeError("All eleven original menu Widget Blueprints must exist; no replacements are created")

    inspector = getattr(unreal, "PHMenuPreviewEditorLibrary", None)
    if args.apply and inspector is None:
        raise RuntimeError("Build ALS_ProjectHunterEditor first; the menu contract checker is required before saving")
    before = None
    if inspector:
        if not inspector.inspect_menu_contracts(str(output / "ContractsBefore.json")):
            raise RuntimeError("Could not inspect the original menu contracts")
        before = functional_contract(json.loads((output / "ContractsBefore.json").read_text(encoding="utf-8")))
    if args.apply:
        backup_assets(output)

    # Before styling: the brushes read the texture size and refuse a
    # non-power-of-two panel texture.
    textures = reimport_system_textures()

    for name, asset in assets.items():
        asset.modify()
        style_asset(name, asset)
        unreal.BlueprintEditorLibrary.compile_blueprint(asset)

    if inspector:
        if not inspector.inspect_menu_contracts(str(output / "ContractsAfter.json")):
            raise RuntimeError("Could not inspect the edited menu contracts; no assets saved")
        after_report = json.loads((output / "ContractsAfter.json").read_text(encoding="utf-8"))
        failed_compiles = [asset["asset"] for asset in after_report["assets"] if not asset.get("compile_ok", False)]
        if failed_compiles:
            raise RuntimeError("Menu Blueprints did not compile cleanly; no assets saved: " + str(failed_compiles))
        after = functional_contract(after_report)
        if before != after:
            raise RuntimeError("A protected Blueprint contract changed; inspect ContractsBefore/After. No assets saved")
        if not inspector.validate_system_menu():
            raise RuntimeError("Menu interaction/binding validation failed; no assets saved")

    if args.apply:
        for asset in list(textures) + list(assets.values()):
            if not unreal.EditorAssetLibrary.save_loaded_asset(asset, only_if_is_dirty=False):
                raise RuntimeError("Asset save failed; verified originals are in BackupManifest.json: " + asset.get_path_name())
    (output / "Result.json").write_text(json.dumps({
        "saved": args.apply, "assets": sorted(targets), "cell_size": CELL_SIZE,
        "palette": PALETTE, "contracts_checked": inspector is not None,
        "note": "Only menu presentation authored. No gameplay, HUD, widget identities, graphs or bindings changed.",
    }, indent=2), encoding="utf-8")
    unreal.log("Menu polish " + ("saved" if args.apply else "exercised in memory only; nothing saved") + ": " + str(output))


if __name__ == "__main__":
    main()
