// Copyright:   Copyright (C) 2022 Quentin Davis
// Source Code: https://github.com/MahouSenseii/ProjectHunter

#pragma once

#include "NativeGameplayTags.h"

/**
 * Semantic anchor vocabulary from GAME_DESIGN §10. Generators publish these poses and scenarios
 * consume them by tag rather than by coordinate, so one scenario works across many map types.
 *
 * A generator need not place every kind, and placing one is not a promise that anything consumes it.
 */
namespace PHGenerationTags
{
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_PlayerStart);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Exit);

	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Enemy);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Enemy_Small);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Enemy_Medium);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Enemy_Large);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Elite);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Boss);

	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Chest);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Treasure);

	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Event);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Event_Small);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Event_Medium);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Event_Large);

	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_NPC);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Rescue);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Ambush);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Defend);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Escort_Start);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Escort_End);

	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Secret);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Trap);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Portal);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Shrine);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anchor_Constellation);

	/**
	 * Logical construction pieces from GAME_DESIGN §11. Generation and construction ask for these;
	 * a biome module set resolves them to real assets. No generator may name a mesh directly, so
	 * the art pack stays replaceable.
	 */
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Piece);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Piece_Wall);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Piece_Wall_Straight);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Piece_Wall_Corner);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Piece_Floor);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Piece_Ceiling);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Piece_Door);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Piece_Stair);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Piece_Pillar);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Piece_Room_Small);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Piece_Room_Large);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Piece_Trap);

	/**
	 * Decoration props from GAME_DESIGN §38. Resolved through the same biome module set as
	 * construction pieces, but placed by the decoration stage from its own stream so clutter can
	 * never shift layout, anchors, encounters, or loot.
	 */
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Barrel);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Barrel_Explosive);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Crate);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Container);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Debris);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Rubble);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Clutter_Small);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Furniture);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Vegetation);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Pipe);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Light);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Light_Ceiling);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Banner);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Corpse);
	ALS_PROJECTHUNTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Prop_Campfire);
}
